# Generated by Django 6.0.5 on 2026-05-29 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('destination', models.CharField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_visited', models.BooleanField(default=False)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='trips.travel')),
            ],
            options={
                'unique_together': {('travel', 'external_id')},
            },
        ),
    ]
