# Generated by Django 6.0.5 on 2026-05-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='destination',
        ),
        migrations.AddField(
            model_name='travel',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
