# Generated by Django 6.0.5 on 2026-05-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_travel_destination_travel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
